apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ctd.fullname" . }}
  labels:
    {{- include "ctd.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ctd.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "ctd.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
