apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctd.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ctd.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data: {} # Injected by ctd-webhook
