apiVersion: v1
kind: Service
metadata:
  name: {{ include "ctd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ctd.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: https-webhook
      port: 443
      targetPort: https-webhook
      protocol: TCP
  selector:
    {{- include "ctd.selectorLabels" . | nindent 4 }}
